package cn.scllll.supercat.Task;

import cn.scllll.supercat.Modules.Operation.OperationBuilder;
import cn.scllll.supercat.Modules.Operation.OperationFactory.OperationClasses.GestureOperation;
import cn.scllll.supercat.Modules.Operation.OperationFactory.OperationClasses.GlobalAction;
import cn.scllll.supercat.Modules.Operation.OperationFactory.OperationFactory;

public class JD {
    public static OperationBuilder earnCoinsJDHighResolution(){
        OperationBuilder builder = OperationBuilder.create()
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(2000))

                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,2100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,2100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,2100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,2100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1900).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1900).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

             /*   .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,2100).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1900).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(540,1175,540,449).select(GestureOperation.SCROLL).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1900).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(540,1175,540,449).select(GestureOperation.SCROLL).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1900).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(540,1175,540,449).select(GestureOperation.SCROLL).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1900).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1100).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(950,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(540,1175,540,449).select(GestureOperation.SCROLL).setDelay(2000))
                .next(OperationFactory.create(GestureOperation.class).add(450,1800).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1500).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))*/

                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_HOME));
        return builder;
    }

    public static OperationBuilder earnCoinsJDNormalResolution(){
        OperationBuilder builder = OperationBuilder.create()
                .next(OperationFactory.create(GestureOperation.class).add(900,1700).select(GestureOperation.CLICK).setDelay(2000))

                .next(OperationFactory.create(GestureOperation.class).add(900,1800).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1900).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1800).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1900).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1800).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1900).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1800).select(GestureOperation.CLICK).setDelay(4000))
                .next(OperationFactory.create(GestureOperation.class).add(300,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,700).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(800,1400).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(300,1900).select(GestureOperation.CLICK).setDelay(2000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1600).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1600).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1400).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))
                .next(OperationFactory.create(GestureOperation.class).add(900,1200).select(GestureOperation.CLICK).setDelay(15000))
                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_BACK))

                .next(OperationFactory.create(GlobalAction.class).add(GlobalAction.ACTION_HOME));
        return builder;
    }

}
